### PR TITLE
Feature/ui

### PR DESCRIPTION
**Pull request by Neevan09**
Added mainmenu screen, opening cut scene, dialogue box.

### CODE REVIEW

**Comment by burhanuddinmb** [comment]
The branch has,
1. Conflicts with master
2. Give me information regarding the Scene, as I am getting a lot of errors.

**Comment by burhanuddinmb** [comment]
Scripts need to be put in appropriate folders.

**Comment by burhanuddinmb** [comment]
Why are character ability scripts here?

**Comment by burhanuddinmb** [comment]
We need to make a game manager. I guess thats a trello task.

**Comment by burhanuddinmb** [comment]
I hope you have gone through the code though once.

**Comment by Neevan09** [comment]
> Why are character ability scripts here?
I want to check.

**Review by burhanuddinmb — APPROVED** [review]
Merge it.

**Pull request merged**
